missing "=" in desktop file
In line 31 a "=" was missing which leads to parsing problems for some apps (f.e. "Insync").

xdg.Exceptions.ParsingError: ParsingError in file '/usr/share/applications/mx-select-sound.desktop', Invalid line: Comment[lt]Lengvai pasirinkti numatytąją garso plokštę